spring:
  profiles:
    active:
      prod
  application:
    name: data-sync
logging:
  config: classpath:log/logback.xml

feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
