server:
  port: 7079

logging:
  path: /var/log/infomanage

spring: 
#  datasource:
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://10.6.205.35:3306/infomanage?useUnicode=true&characterEncoding=utf-8
#    username: ci
#    password: ci
#  datasource_cdp:
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://10.6.205.35:3306/cdp?useUnicode=true&characterEncoding=utf-8
#    username: ci
#    password: ci
#  datasource_ci:
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://10.6.205.35:3306/ci?useUnicode=true&characterEncoding=utf-8
#    username: ci
#    password: ci
#    url: jdbc:mysql://192.168.114.129:3306/infomanage?useUnicode=true&characterEncoding=utf-8
#    username: root
#    password: root
  data:
    mongodb:
      primary:
#      host: 10.7.201.43:7210 10.6.205.32:27017
#      port: 7210
#      host: 192.168.114.129
#      port: 27017
#        uri: 10.7.201.43:7210
#        database: cc_data_20180704
#      secondary:
#        uri: 10.7.201.43:7210
#        database: cc
#      tertiary:
#        uri: 10.7.201.43:7210
#        database: bill
        uri: 10.6.205.32:27017
        database: cc_data_201807041
#      secondary:
#        uri: 10.6.205.32:27017
#        database: cc
#      tertiary:
#        uri: 10.6.205.32:27017
#        database: bill
#
#eureka:
#  client:
#    enabled: true
#    eureka-server-read-timeout-seconds: 25
#    eureka-server-connect-timeout-seconds: 20
#    eureka-connection-idle-timeout-seconds: 25
#    register-with-eureka: true
#    serviceUrl:
#      defaultZone: http://10.6.205.20:7077/eureka/
#  instance:
#    lease-renewal-interval-in-seconds: 10
#    lease-expiration-duration-in-seconds: 300

#faw:
#  url: http://10.6.205.16:8081
#dms:
#  url: http://dmstest.hq.faw.cn:8000
#tps:
#  url: http://10.6.222.96:60080
jobs:
  cron: 0 0/30 * * * ?
  final: 0 0 0 * * ?
  shour: 0 0 1,3,5,7,9,11,13,15,17,19,21,23 * * ?
  dhour: 0 0 0,2,4,6,8,10,12,14,16,18,20,22 * * ?
