server:
  port: 7079

logging:
#  path: /var/log/dateSync
  path: E:/tmp/log/infomanage

spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:oracle:thin:@10.133.80.121:1521:GMM
      username: gmmhl
      password: gmmhl
      initialSize: 20
      minIdle: 20
      maxActive: 200
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 30000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
#      driver-class-name: oracle.jdbc.OracleDriver
#    url: jdbc:oracle:thin:@10.133.89.117:1521:crmreport
#    username: crm_zhsw
#    password: crm_zhsw
#    url: jdbc:oracle:thin:@10.133.80.121:1521:GMM
#    username: GMMHL
#    password: gmmhl
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    mongodb:
      primary:
#        uri: 10.7.201.43:7210
#        database: cc_data_20180704
        uri: 10.6.205.32:27017
        database: cc_data_201807041

jobs:
  cron: 0 0 2 * * ?
  final: 0 0 1 * * ?
  shour: 0 0 1,3,5,7,9,11,13,15,17,19,21,23 * * ?
  dhour: 0 0 0,2,4,6,8,10,12,14,16,18,20,22 * * ?
